name: Extract and Commit IPs

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 手动触发

jobs:
  extract_ips:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 提取IP地址
        run: |
          curl -o result.txt https://raw.githubusercontent.com/BruceWind/GcoreCDNIPSelector/refs/heads/main/result.txt
          grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' result.txt > ips.txt

      - name: 提交更改
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ips.txt
          git commit -m "Update extracted IPs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
