$ git credential-osxkeychain erase
host=github.com
protocol=https
> [Press Return]
name: Update API Data

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run API data fetch script
      run: python fetch_api_data.py

    - name: Configure Git
      run: |
        git config --global user.name "eliangwww"
        git config --global user.email "1139523599@qq.com"

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git add api_data.txt
        git commit -m "Update API data"
        git push origin HEAD:${{ github.ref }}
